---
- name: INSTALL HELM | Set common facts
  ansible.builtin.set_fact:
    helm_url: https://get.helm.sh/helm-{{ install_helm_version }}-linux-{{ install_helm_arch }}.tar.gz

- name: INSTALL HELM | Set current helm version
  ansible.builtin.command:
    cmd: /usr/local/bin/helm version --client --template={% raw %}"{{ .Version }}"{% endraw %}
  changed_when: false
  failed_when: false
  register: current_helm_version

- name: INSTALL HELM | Download helm archive
  ansible.builtin.get_url:
    url: "{{ helm_url }}"
    checksum: "sha256:{{ helm_url }}.sha256sum"
    dest: /tmp
    owner: root
    group: root
    mode: "0644"
  notify: Unarchive helm binary
  when: install_helm_version != current_helm_version.stdout | default(false)

- name: INSTALL HELM | Flush handlers
  ansible.builtin.meta: flush_handlers

- name: INSTALL HELM | Delete helm archive
  ansible.builtin.file:
    path: /tmp/helm-{{ install_helm_version }}-linux-{{ install_helm_arch }}.tar.gz
    state: absent

- name: INSTALL HELM | Delete unarchived helm files
  ansible.builtin.file:
    path: /tmp/linux-{{ install_helm_arch }}/
    state: absent
