---
- name: INSTALL HELM | Unarchive helm binary
  ansible.builtin.unarchive:
    src: /tmp/helm-{{ install_helm__version }}-linux-{{ install_helm__arch }}.tar.gz
    dest: /tmp
    remote_src: true
  listen: Unarchive helm binary

- name: INSTALL HELM | Copy unarchived helm binary to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/linux-{{ install_helm__arch }}/helm
    dest: /usr/local/bin
    mode: "0755"
    remote_src: true
  listen: Unarchive helm binary
